sudo: required
os: linux
services:
  - docker

language: python

script:
  - pytest
 # - python3 tests/test_generator.py && tests/test_parser_vk.py

#after_success:
#  - sh .travis/deploy_dockerhub.sh
#  - sh .travis/deploy_heroku.sh
